### ISSUE TITLE
Use interrupts instead of hot idling

### ISSUE THREAD

**Issue by danielbuechele** [abobija/esp-idf-rc522#36]
Currently, when waiting for a tag, the task is put to sleep for 100ms and then activated again. The MFRC522 module has a IRQ pin and we could use an interrupt when the tag is present.

**Comment by abobija** [comment]
Hi,

I'm sorry for not getting back to you sooner. I'm currently working on upgrading some parts of this library and I've revisited this issue.

I checked into using interrupts with the MFRC522, and here’s why polling is required:

Although the MFRC522 supports interrupts (like RxIRq), they only trigger after the reader receives a response from a card. For the card to respond, the reader must first send commands to initiate communication. Since the card doesn’t send data on its own, these commands need to be sent periodically, effectively meaning polling is still necessary.

Hope this clarifies!
